# Node.js Function App to Windows on Azure
# Build a Node.js function app and deploy it to Azure as a Windows function app.
# Add steps that build code, save build artifacts, deploy, and more:

on:
  push:
    branches:
      - master

name: Build and deploy queue function

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - uses: actions/checkout@master

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_88292c7b }}

      - name: "Run npm"
        shell: bash
        working-directory: backend
        run: |
          # If your function app project is not located in your repository's root
          # Please change your directory for npm in pushd
          pushd .
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      # deploy web app using publish profile credentials
      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        with:
          app-name: aapowellpowerfuldev-backend-backup
          package: .

      # Azure logout
      - name: logout
        run: |
          az logout
